# @packageDocumentation
# Frontend: pubspec.yaml
# Backend: Not implemented
# API: Not implemented
# QA: Not implemented

name: frontend
description: MentorinAja Flutter frontend

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/auth/
    - assets/icons/banners/
    - assets/icons/language/
    - assets/icons/logo/
    - assets/icons/onboarding/
    - assets/audio/
    - assets/fonts/
    - assets/translations/
